# Generated by Django 5.2.8 on 2025-12-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tests_done',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medicines',
            field=models.TextField(blank=True),
        ),
    ]
